key_map_json = \
{
        "01": [{"keysym": "Escape", "vk": "VK_ESCAPE", "label": "Esc"},         {"keysym": "Escape", "vk": "VK_ESCAPE", "label": "Esc"},        {"keysym": "Escape", "vk": "VK_ESCAPE", "label": "Esc"},    {"keysym": "Escape", "vk": "VK_ESCAPE", "label": "Esc"},        {"keysym": "Escape", "vk": "VK_ESCAPE", "label": "Esc"},            {"keysym": "Escape", "vk": "VK_ESCAPE", "label": "Esc"}],
        "29": [{"keysym": "dead_circumflex", "char": "^", "label": "\u02c6"},   {"keysym": "dead_caron", "char": "\u02c7"},                     {"keysym": "U21BB", "char": "\u21bb"},                      {"keysym": "dead_abovedot", "char": "\u02d9"},                  {"keysym": "U02DE", "char": "\u02de"},                              {"keysym": "dead_belowdot", "char": "."}],
        "0D": [{"keysym": "dead_grave", "char": "\u0060", "label": "\u02cb"},   {"keysym": "dead_cedilla", "char": "\u00b8"},                   {"keysym": "dead_abovering", "char": "\u02da"},             {"keysym": "dead_diaeresis", "char": "\u00a8"},                 {"keysym": "dead_dasia", "char": "\u1ffe"},                         {"keysym": "dead_macron", "char": "\u00af"}],
        "1B": [{"keysym": "dead_acute", "char": "\u00b4", "label": "\u02ca"},   {"keysym": "dead_tilde", "char": "~", "label": "\u02dc"},       {"keysym": "dead_stroke", "char": "\u002f"},                {"keysym": "dead_doubleacute", "char": "\u02dd"},               {"keysym": "dead_psili", "char": "\u1fbf"},                         {"keysym": "dead_breve", "char": "\u02d8"}],
                
        "02": [{"keysym": "1", "char": "1"},                                    {"keysym": "degree", "char": "°"},                              {"keysym": "onesuperior", "char": "¹"},                     {"keysym": "ordfeminine", "char": "ª"},                         {"keysym": "onesubscript", "char": "₁"},                            {"keysym": "notsign", "char": "¬"}],
        "03": [{"keysym": "2", "char": "2"},                                    {"keysym": "section", "char": "§"},                             {"keysym": "twosuperior", "char": "²"},                     {"keysym": "masculine", "char": "º"},                           {"keysym": "twosubscript", "char": "₂"},                            {"keysym": "logicalor", "char": "∨"}],
        "04": [{"keysym": "3", "char": "3"},                                    {"keysym": "U2113", "char": "ℓ"},                               {"keysym": "threesuperior", "char": "³"},                   {"keysym": "numerosign", "char": "№"},                          {"keysym": "threesubscript", "char": "₃"},                          {"keysym": "logicaland", "char": "∧"}],
        "05": [{"keysym": "4", "char": "4"},                                    {"keysym": "guillemotright", "char": "»"},                      {"keysym": "U203A", "char": "›"},                           {},                                                             {"keysym": "femalesymbol", "char": "\u2640"},                       {"keysym": "uptack", "char": "⊥"}],
        "06": [{"keysym": "5", "char": "5"},                                    {"keysym": "guillemotleft", "char": "«"},                       {"keysym": "U2039", "char": "‹"},                           {"keysym": "periodcentered", "char": "·"},                      {"keysym": "malesymbol", "char": "\u2642"},                         {"keysym": "U2221", "char": "∡"}],
        "07": [{"keysym": "6", "char": "6"},                                    {"keysym": "dollar", "char": "$"},                              {"keysym": "cent", "char": "¢"},                            {"keysym": "sterling", "char": "£"},                            {"keysym": "U26A5", "char": "\u26A5"},                              {"keysym": "U2225", "char": "∥"}],
        "08": [{"keysym": "7", "char": "7"},                                    {"keysym": "EuroSign", "char": "€"},                            {"keysym": "yen", "char": "¥"},                             {"keysym": "currency", "char": "¤"},                            {"keysym": "U03F0", "char": "ϰ"},                                   {"keysym": "rightarrow", "char": "→"}],
        "09": [{"keysym": "8", "char": "8"},                                    {"keysym": "doublelowquotemark", "char": "„"},                  {"keysym": "singlelowquotemark", "char": "‚"},              {"keysym": "Tab", "vk": "VK_TAB", "label": "\u21b9"},           {"keysym": "leftanglebracket", "char": "\u27E8"},                   {"keysym": "infinity", "char": "∞"}],
        "0A": [{"keysym": "9", "char": "9"},                                    {"keysym": "leftdoublequotemark", "char": "“"},                 {"keysym": "leftsinglequotemark", "char": "‘"},             {"keysym": "KP_Divide", "vk": "VK_DIVIDE", "label": "÷"},       {"keysym": "rightanglebracket", "char": "\u27E9"},                  {"keysym": "variation", "char": "∝"}],
        "0B": [{"keysym": "0", "char": "0"},                                    {"keysym": "rightdoublequotemark", "char": "”"},                {"keysym": "rightsinglequotemark", "char": "’"},            {"keysym": "KP_Multiply", "vk": "VK_MULTIPLY", "label": "×"},   {"keysym": "zerosubscript", "char": "₀"},                           {"keysym": "emptyset", "char": "∅"}],
                
        "1C": [{"keysym": "Return", "vk": "VK_RETURN", "label": "\u21a9"},      {"keysym": "Return", "vk": "VK_RETURN", "label": "\u21a9"},     {"keysym": "Return", "vk": "VK_RETURN", "label": "\u21a9"}, {"keysym": "Return", "vk": "VK_RETURN", "label": "\u21a9"},     {"keysym": "Return", "vk": "VK_RETURN", "label": "\u21a9"},         {"keysym": "Return", "vk": "VK_RETURN", "label": "\u21a9"}],
        "0F": [{"keysym": "Tab", "vk": "VK_TAB", "label": "\u21b9"},            {"keysym": "Tab", "vk": "VK_TAB", "label": "\u21b9"},           {"keysym": "Multi_key", "char": "\u266B"},                  {"keysym": "Tab", "vk": "VK_TAB", "label": "\u21b9"},           {},                                                                 {}],
        "39": [{"keysym": "space", "vk": "VK_SPACE", "label": "\u2423"},        {"keysym": "space", "vk": "VK_SPACE", "label": "\u2423"},       {"keysym": "space", "vk": "VK_SPACE", "label": "\u2423"},   {"keysym": "KP_0", "vk": "VK_NUMPAD0", "label": "0"},           {"keysym": "nobreakspace", "char": "\u00a0", "label": "\u237d"},    {"keysym": "U202F", "char": "\u202f", "label": "\u00a6"}],
                
        "45+":[{"keysym": "Tab", "vk": "VK_TAB", "label": "\u21b9"},            {"keysym": "Tab", "vk": "VK_TAB", "label": "\u21b9"},           {"keysym": "equal", "char": "="},                           {"keysym": "notequal", "char": "≠"},                            {"keysym": "U2248", "char": "≈"},                                   {"keysym": "identical", "char": "≡"}],
        "35+":[{"keysym": "KP_Divide", "vk": "VK_DIVIDE", "label": "÷"},        {"keysym": "KP_Divide", "vk": "VK_DIVIDE", "label": "÷"},       {"keysym": "division", "char": "÷"},                        {"keysym": "U2044", "char": "⁄"},                               {"keysym": "U2300", "char": "⌀"},                                   {"keysym": "U2223", "char": "∣"}],
        "37": [{"keysym": "KP_Multiply", "vk": "VK_MULTIPLY", "label": "×"},    {"keysym": "KP_Multiply", "vk": "VK_MULTIPLY", "label": "×"},   {"keysym": "U22C5", "char": "\u22c5"},                      {"keysym": "multiply", "char": "×"},                            {"keysym": "U2299", "char": "\u2299"},                              {"keysym": "U2297", "char": "\u2297"}],
        "4A": [{"keysym": "KP_Subtract", "vk": "VK_SUBTRACT", "label": "-"},    {"keysym": "KP_Subtract", "vk": "VK_SUBTRACT", "label": "-"},   {"keysym": "U2212", "char": "−"},                           {"keysym": "U2216", "char": "∖"},                               {"keysym": "U2296", "char": "\u2296"},                              {"keysym": "U2238", "char": "\u2238"}],
        "4E": [{"keysym": "KP_Add", "vk": "VK_ADD", "label": "+"},              {"keysym": "KP_Add", "vk": "VK_ADD", "label": "+"},             {"keysym": "plusminus", "char": "±"},                       {"keysym": "U2213", "char": "\u2213"},                          {"keysym": "U2295", "char": "\u2295"},                              {"keysym": "U2214", "char": "∔"}],
        "47": [{"keysym": "KP_7", "vk": "VK_NUMPAD7", "label": "7"},            {"keysym": "U2714", "char": "\u2714"},                          {"keysym": "U2195", "char": "↕"},                           {"keysym": "KP_Home", "vk": "VK_HOME", "label": "\u2196"},      {"keysym": "U226A", "char": "\u226a"},                              {"keysym": "upstile", "char": "⌈"}],
        "48": [{"keysym": "KP_8", "vk": "VK_NUMPAD8", "label": "8"},            {"keysym": "U2718", "char": "\u2718"},                          {"keysym": "uparrow", "char": "↑"},                         {"keysym": "KP_Up", "vk": "VK_UP", "label": "\u2191"},          {"keysym": "intersection", "char": "∩"},                            {"keysym": "U22C2", "char": "⋂"}],
        "49": [{"keysym": "KP_9", "vk": "VK_NUMPAD9", "label": "9"},            {"keysym": "dagger", "char": "†"},                              {"keysym": "U20D7", "char": "\u20d7"},                      {"keysym": "KP_Page_Up", "vk": "VK_PRIOR", "label": "\u21de"},  {"keysym": "U226B", "char": "\u226b"},                              {"keysym": "U2309", "char": "⌉"}],
        "4B": [{"keysym": "KP_4", "vk": "VK_NUMPAD4", "label": "4"},            {"keysym": "club", "char": "\u2663"},                           {"keysym": "leftarrow", "char": "←"},                       {"keysym": "KP_Left", "vk": "VK_LEFT", "label": "\u2190"},      {"keysym": "includedin", "char": "\u2282"},                         {"keysym": "U2286", "char": "⊆"}],
        "4C": [{"keysym": "KP_5", "vk": "VK_NUMPAD5", "label": "5"},            {"keysym": "EuroSign", "char": "€"},                            {"keysym": "colon", "char": ":"},                           {"keysym": "VoidSymbol", "vk": "VK_LBUTTON"},                   {"keysym": "U22B6", "char": "\u22B6"},                              {"keysym": "U22B7", "char": "⊷"}],
        "4D": [{"keysym": "KP_6", "vk": "VK_NUMPAD6", "label": "6"},            {"keysym": "U2023", "char": "\u2023"},                          {"keysym": "rightarrow", "char": "→"},                      {"keysym": "KP_Right", "vk": "VK_RIGHT", "label": "\u2192"},    {"keysym": "includes", "char": "\u2283"},                           {"keysym": "U2287", "char": "⊇"}],
        "4F": [{"keysym": "KP_1", "vk": "VK_NUMPAD1", "label": "1"},            {"keysym": "diamond", "char": "\u2666"},                        {"keysym": "U2194", "char": "↔"},                           {"keysym": "KP_End", "vk": "VK_END", "label": "\u2198"},        {"keysym": "lessthanequal", "char": "≤"},                           {"keysym": "downstile", "char": "⌊"}],
        "50": [{"keysym": "KP_2", "vk": "VK_NUMPAD2", "label": "2"},            {"keysym": "heart", "char": "\u2665"},                          {"keysym": "downarrow", "char": "↓"},                       {"keysym": "KP_Down", "vk": "VK_DOWN", "label": "\u2193"},      {"keysym": "union", "char": "\u222A"},                              {"keysym": "U22C3", "char": "\u22c3"}],
        "51": [{"keysym": "KP_3", "vk": "VK_NUMPAD3", "label": "3"},            {"keysym": "U2660", "char": "\u2660"},                          {"keysym": "U21CC", "char": "\u21cc"},                      {"keysym": "KP_Page_Down", "vk": "VK_NEXT", "label": "\u21df"}, {"keysym": "greaterthanequal", "char": "≥"},                        {"keysym": "U230B", "char": "⌋"}],
        "52": [{"keysym": "KP_0", "vk": "VK_NUMPAD0", "label": "0"},            {"keysym": "signifblank", "char": "\u2423"},                    {"keysym": "percent", "char": "%"},                         {"keysym": "KP_Insert", "vk": "VK_INSERT", "label": "Ins"},     {"keysym": "permille", "char": "‰"},                                {"keysym": "U25A1", "char": "□"}],
        "53": [{"keysym": "KP_Separator", "vk": "VK_DECIMAL", "label": ","},    {"keysym": "period", "char": "."},                              {"keysym": "comma", "vk": "VK_OEM_COMMA", "label": ","},    {"keysym": "KP_Delete", "vk": "VK_DELETE", "label": "\u2326"},  {"keysym": "minutes", "char": "′"},                                 {"keysym": "seconds", "char": "″"}],
        
        "0C": [{"keysym": "ssharp", "char": "ß"},                               {"keysym": "U1E9E", "char": "\u1e9e"},                          {},                                                         {"keysym": "KP_Subtract", "vk": "VK_SUBTRACT", "label": "-"},   {"keysym": "Greek_finalsmallsigma", "char": "ς"},                   {"keysym": "jot", "char": "∘"}],
        "10": [{"keysym": "q", "vk": "VK_KEY_Q", "label": "q"},                 {"keysym": "Q", "vk": "VK_KEY_Q", "label": "Q"},                {"keysym": "ellipsis", "char": "…"},                        {"keysym": "Page_Up", "vk": "VK_PRIOR", "label": "\u21de"},     {"keysym": "U03D5", "char": "ϕ"},                                   {"keysym": "U211A", "char": "ℚ"}],
        "11": [{"keysym": "w", "vk": "VK_KEY_W", "label": "w"},                 {"keysym": "W", "vk": "VK_KEY_W", "label": "W"},                {"keysym": "underscore", "char": "_"},                      {"keysym": "BackSpace", "vk": "VK_BACK", "label": "\u232b"},    {"keysym": "Greek_omega", "char": "ω"},                             {"keysym": "Greek_OMEGA", "char": "Ω"}],
        "12": [{"keysym": "e", "vk": "VK_KEY_E", "label": "e"},                 {"keysym": "E", "vk": "VK_KEY_E", "label": "E"},                {"keysym": "bracketleft", "char": "["},                     {"keysym": "Up", "vk": "VK_UP", "label": "\u2191"},             {"keysym": "Greek_epsilon", "char": "ε"},                           {"keysym": "U2203", "char": "∃"}],
        "13": [{"keysym": "r", "vk": "VK_KEY_R", "label": "r"},                 {"keysym": "R", "vk": "VK_KEY_R", "label": "R"},                {"keysym": "bracketright", "char": "]"},                    {"keysym": "Delete", "vk": "VK_DELETE", "label": "\u2326"},     {"keysym": "Greek_rho", "char": "ρ"},                               {"keysym": "U211D", "char": "ℝ"}],
        "14": [{"keysym": "t", "vk": "VK_KEY_T", "label": "t"},                 {"keysym": "T", "vk": "VK_KEY_T", "label": "T"},                {"keysym": "asciicircum", "char": "^"},                     {"keysym": "Page_Down", "vk": "VK_NEXT", "label": "\u21df"},    {"keysym": "Greek_tau", "char": "τ"},                               {"keysym": "partdifferential", "char": "∂"}],
        "15": [{"keysym": "z", "vk": "VK_KEY_Z", "label": "z"},                 {"keysym": "Z", "vk": "VK_KEY_Z", "label": "Z"},                {"keysym": "exclam", "char": "!"},                          {"keysym": "exclamdown", "char": "¡"},                          {"keysym": "Greek_zeta", "char": "ζ"},                              {"keysym": "U2124", "char": "ℤ"}],
        "16": [{"keysym": "u", "vk": "VK_KEY_U", "label": "u"},                 {"keysym": "U", "vk": "VK_KEY_U", "label": "U"},                {"keysym": "less", "char": "<"},                            {"keysym": "KP_7", "vk": "VK_NUMPAD7", "label": "7"},           {},                                                                 {"keysym": "includedin", "char": "⊂"}],
        "17": [{"keysym": "i", "vk": "VK_KEY_I", "label": "i"},                 {"keysym": "I", "vk": "VK_KEY_I", "label": "I"},                {"keysym": "greater", "char": ">"},                         {"keysym": "KP_8", "vk": "VK_NUMPAD8", "label": "8"},           {"keysym": "Greek_iota", "char": "ι"},                              {"keysym": "integral", "char": "∫"}],
        "18": [{"keysym": "o", "vk": "VK_KEY_O", "label": "o"},                 {"keysym": "O", "vk": "VK_KEY_O", "label": "O"},                {"keysym": "equal", "char": "="},                           {"keysym": "KP_9", "vk": "VK_NUMPAD9", "label": "9"},           {"keysym": "Greek_omicron", "char": "ο"},                           {"keysym": "elementof", "char": "∈"}],
        "19": [{"keysym": "p", "vk": "VK_KEY_P", "label": "p"},                 {"keysym": "P", "vk": "VK_KEY_P", "label": "P"},                {"keysym": "ampersand", "char": "&"},                       {"keysym": "KP_Add", "vk": "VK_ADD", "label": "+"},             {"keysym": "Greek_pi", "char": "π"},                                {"keysym": "Greek_PI", "char": "Π"}],
        "1A": [{"keysym": "udiaeresis", "char": "ü"},                           {"keysym": "Udiaeresis", "char": "Ü"},                          {"keysym": "U017F", "char": "ſ"},                           {"keysym": "U2212", "char": "−"},                               {},                                                                 {"keysym": "union", "char": "∪"}],
        "1E": [{"keysym": "a", "vk": "VK_KEY_A", "label": "a"},                 {"keysym": "A", "vk": "VK_KEY_A", "label": "A"},                {"keysym": "backslash", "char": "\\"},                      {"keysym": "Home", "vk": "VK_HOME", "label": "\u2196"},         {"keysym": "Greek_alpha", "char": "α"},                             {"keysym": "U2200", "char": "∀"}],
        "1F": [{"keysym": "s", "vk": "VK_KEY_S", "label": "s"},                 {"keysym": "S", "vk": "VK_KEY_S", "label": "S"},                {"keysym": "slash", "char": "/"},                           {"keysym": "Left", "vk": "VK_LEFT", "label": "\u2190"},         {"keysym": "Greek_sigma", "char": "σ"},                             {"keysym": "Greek_SIGMA", "char": "Σ"}],
        "20": [{"keysym": "d", "vk": "VK_KEY_D", "label": "d"},                 {"keysym": "D", "vk": "VK_KEY_D", "label": "D"},                {"keysym": "braceleft", "char": "{"},                       {"keysym": "Down", "vk": "VK_DOWN", "label": "\u2193"},         {"keysym": "Greek_delta", "char": "δ"},                             {"keysym": "Greek_DELTA", "char": "Δ"}],
        "21": [{"keysym": "f", "vk": "VK_KEY_F", "label": "f"},                 {"keysym": "F", "vk": "VK_KEY_F", "label": "F"},                {"keysym": "braceright", "char": "}"},                      {"keysym": "Right", "vk": "VK_RIGHT", "label": "\u2192"},       {"keysym": "Greek_phi", "char": "φ"},                               {"keysym": "Greek_PHI", "char": "Φ"}],
        "22": [{"keysym": "g", "vk": "VK_KEY_G", "label": "g"},                 {"keysym": "G", "vk": "VK_KEY_G", "label": "G"},                {"keysym": "asterisk", "char": "*"},                        {"keysym": "End", "vk": "VK_END", "label": "\u2198"},           {"keysym": "Greek_gamma", "char": "γ"},                             {"keysym": "Greek_GAMMA", "char": "Γ"}],
        "23": [{"keysym": "h", "vk": "VK_KEY_H", "label": "h"},                 {"keysym": "H", "vk": "VK_KEY_H", "label": "H"},                {"keysym": "question", "char": "?"},                        {"keysym": "questiondown", "char": "¿"},                        {"keysym": "Greek_psi", "char": "ψ"},                               {"keysym": "Greek_PSI", "char": "Ψ"}],
        "24": [{"keysym": "j", "vk": "VK_KEY_J", "label": "j"},                 {"keysym": "J", "vk": "VK_KEY_J", "label": "J"},                {"keysym": "parenleft", "char": "("},                       {"keysym": "KP_4", "vk": "VK_NUMPAD4", "label": "4"},           {"keysym": "Greek_theta", "char": "θ"},                             {"keysym": "Greek_THETA", "char": "Θ"}],
        "25": [{"keysym": "k", "vk": "VK_KEY_K", "label": "k"},                 {"keysym": "K", "vk": "VK_KEY_K", "label": "K"},                {"keysym": "parenright", "char": ")"},                      {"keysym": "KP_5", "vk": "VK_NUMPAD5", "label": "5"},           {"keysym": "Greek_kappa", "char": "κ"},                             {"keysym": "multiply", "char": "×"}],
        "26": [{"keysym": "l", "vk": "VK_KEY_L", "label": "l"},                 {"keysym": "L", "vk": "VK_KEY_L", "label": "L"},                {"keysym": "minus", "char": "-"},                           {"keysym": "KP_6", "vk": "VK_NUMPAD6", "label": "6"},           {"keysym": "Greek_lamda", "char": "λ"},                             {"keysym": "Greek_LAMDA", "char": "Λ"}],
        "27": [{"keysym": "odiaeresis", "char": "ö"},                           {"keysym": "Odiaeresis", "char": "Ö"},                          {"keysym": "colon", "char": ":"},                           {"keysym": "KP_Separator", "vk": "VK_DECIMAL", "label": ","},   {"keysym": "U03F5", "char": "ϵ"},                                   {"keysym": "intersection", "char": "∩"}],
        "28": [{"keysym": "adiaeresis", "char": "ä"},                           {"keysym": "Adiaeresis", "char": "Ä"},                          {"keysym": "at", "char": "@"},                              {"keysym": "period", "char": "."},                              {"keysym": "Greek_eta", "char": "η"},                               {"keysym": "U2135", "char": "ℵ"}],
        "2C": [{"keysym": "y", "vk": "VK_KEY_Y", "label": "y"},                 {"keysym": "Y", "vk": "VK_KEY_Y", "label": "Y"},                {"keysym": "numbersign", "char": "#"},                      {"keysym": "Escape", "vk": "VK_ESCAPE", "label": "\u238b"},     {"keysym": "Greek_upsilon", "char": "υ"},                           {"keysym": "nabla", "char": "∇"}],
        "2D": [{"keysym": "x", "vk": "VK_KEY_X", "label": "x"},                 {"keysym": "X", "vk": "VK_KEY_X", "label": "X"},                {"keysym": "dollar", "char": "$"},                          {"keysym": "Tab", "vk": "VK_TAB", "label": "\u21b9"},           {"keysym": "Greek_xi", "char": "ξ"},                                {"keysym": "Greek_XI", "char": "Ξ"}],
        "2E": [{"keysym": "c", "vk": "VK_KEY_C", "label": "c"},                 {"keysym": "C", "vk": "VK_KEY_C", "label": "C"},                {"keysym": "bar", "char": "|"},                             {"keysym": "Insert", "vk": "VK_INSERT", "label": "Ins"},        {"keysym": "Greek_chi", "char": "χ"},                               {"keysym": "U2102", "char": "ℂ"}],
        "2F": [{"keysym": "v", "vk": "VK_KEY_V", "label": "v"},                 {"keysym": "V", "vk": "VK_KEY_V", "label": "V"},                {"keysym": "asciitilde", "char": "~"},                      {"keysym": "Return", "vk": "VK_RETURN", "label": "\u21a9"},     {},                                                                 {"keysym": "radical", "char": "√"}],
        "30": [{"keysym": "b", "vk": "VK_KEY_B", "label": "b"},                 {"keysym": "B", "vk": "VK_KEY_B", "label": "B"},                {"keysym": "grave", "char": "`"},                           {"vk": "VK_KEY_Z", "mods": {"Ctrl": True}, "label": "\u238c"},  {"keysym": "Greek_beta", "char": "β"},                              {"keysym": "U21D0", "char": "⇐"}],
        "31": [{"keysym": "n", "vk": "VK_KEY_N", "label": "n"},                 {"keysym": "N", "vk": "VK_KEY_N", "label": "N"},                {"keysym": "plus", "char": "+"},                            {"keysym": "colon", "char": ":"},                               {"keysym": "Greek_nu", "char": "ν"},                                {"keysym": "U2115", "char": "ℕ"}],
        "32": [{"keysym": "m", "vk": "VK_KEY_M", "label": "m"},                 {"keysym": "M", "vk": "VK_KEY_M", "label": "M"},                {"keysym": "percent", "char": "%"},                         {"keysym": "KP_1", "vk": "VK_NUMPAD1", "label": "1"},           {"keysym": "Greek_mu", "char": "μ"},                                {"keysym": "ifonlyif", "char": "⇔"}],
        "33": [{"keysym": "comma", "char": ","},                                {"keysym": "endash", "char": "–"},                              {"keysym": "quotedbl", "char": "\""},                       {"keysym": "KP_2", "vk": "VK_NUMPAD2", "label": "2"},           {"keysym": "U03F1", "char": "ϱ"},                                   {"keysym": "implies", "char": "⇒"}],
        "34": [{"keysym": "period", "char": "."},                               {"keysym": "enfilledcircbullet", "char": "•"},                  {"keysym": "apostrophe", "char": "'"},                      {"keysym": "KP_3", "vk": "VK_NUMPAD3", "label": "3"},           {"keysym": "U03D1", "char": "ϑ"},                                   {"keysym": "U21A6", "char": "↦"}],
        "35": [{"keysym": "minus", "vk": "VK_OEM_MINUS", "label": "-"},         {"keysym": "emdash", "char": "—"},                              {"keysym": "semicolon", "char": ";"},                       {"keysym": "semicolon", "char": ";"},                           {"keysym": "U2011", "char": "‑"},                                   {"keysym": "U00AD", "char": "\u00ad"}]
        }

# Load JSON into dictionary
# key_map = json.loads(key_map_json)
key_map = key_map_json

def generate_typst_content(key_map):
    typst_content = ''
    typst_content += '#import "preamble.typ": *\n'
    # typst_content += '#grid(columns:7, gutter: 10pt, row-gutter: 10pt,\n'
    typst_content += '#grid(columns:11,\n'
    
    for keycode, key_layers in key_map.items():
        typst_content += f"// Key {keycode}\n"
        
        keys = [0,1,2,3]
        for i, key in enumerate(keys):
            k = key_layers[key]
            if "label" in k:
                keys[i] = k["label"]
            elif "char" in k:
                keys[i] = k["char"]
            else:
                keys[i] = ""
            
        for i, key in enumerate(keys):
            keys[i] = key.replace("\\", "\\\\").replace('"', '\\"')
        
        typst_content += f"keycapbox(\"{keys[0]}\", \"{keys[1]}\", \"{keys[2]}\", \"{keys[3]}\"),\n"
        
    typst_content += ");\n"

    return typst_content

typst_content = generate_typst_content(key_map)

with open("keymap.typ", "w") as file:
    file.write(typst_content)

print("Typst file 'keymap.typ' generated successfully!")
